---
- hosts: all
  become: true
  tasks:

  - name: Update APT package manager
    apt:
      update_cache: yes

  - name: install python3-pip
    apt:
      name: python3-pip

  - name: install python3 package
    apt:
      name:
        - python3

  - name: install java open-jdk
    become: yes
    apt:
      name: "{{packages}}"
      state: present
    vars:
     packages:
       - openjdk-11-jdk
