---
- hosts: all
  become: true
  tasks:

  - name: Update APT package manager
    apt:
      update_cache: yes
  - name: install python3-pip
    apt:
      name: python3-pip
  - name: install python3 package
    apt:
      name: python3
  - name: install python-pip
    apt:
      name: python-pip
  - name: install python package
    apt:
      name: python3
  - name: install ansible-java
    apt: 
      name: ansible-java
